language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - rustup component add clippy
  - cargo build --verbose
  - cargo test --verbose
  - ( cd finalfusion-utils ; cargo build --verbose --features "opq reductive/openblas" )
  - cargo clippy
matrix:
  allow_failures:
    - rust: nightly
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
